services:
  - type: web
    name: franchise-api
    runtime: docker
    repo: https://github.com/JAristi/franchise-api  # ← CAMBIA ESTO
    branch: master
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://${RDS_ENDPOINT}:3306/franchise_db
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: Admin123!
      - key: SERVER_PORT
        value: 8080